### ISSUE TITLE
Android Intent Search Not Working

### ISSUE THREAD

**Issue by Sliicy** [Sefaria/Sefaria-Mobile#50]
I'm having trouble understanding how to perform a search with the Android version of Sefaria via an intent.
For example:
If I want to search for all instances of the word _משה_, I would execute:
`adb.exe shell am start -W -a android.intent.action.VIEW -d  "https://www.sefaria.org/search?q=משה" org.sefaria.sefaria`
But instead of searching for _משה_, the app just displays the Main Menu page (search bar, history, saved, Tanakh, etc.).
What should the URL contain when executing a search from outside the app?
This behavior also happens with English (_Moshe_):
`adb.exe shell am start -W -a android.intent.action.VIEW -d  "https://www.sefaria.org/search?q=Moshe" org.sefaria.sefaria`

Thanks!

**Comment by nsantacruz** [comment]
@Sliicy Thank you for the bug report! First of all, you need to at least pass the `tab` query param to specify what type of search you're doing (try switching tabs on sefaria.org/search?q=moses between "Sources" and "Sheets" and see the param change).

Second, you apparently need to escape ampersands when running `adb.exe`. E.g. this should work: `adb.exe shell am start -W -a android.intent.action.VIEW -d "https://www.sefaria.org/search?q=moses\&tab=text" org.sefaria.sefaria` (at least on my Mac terminal that's necessary)

Third, you helped me uncover a bug with deep linking for search which is fixed in [this patch](https://github.com/Sefaria/Sefaria-Mobile/commit/f9a4e6b20b1fdfc44cf7da5dda6b90aac6a8a496). Will be released soon.

**Comment by Sliicy** [comment]
Thank you @nsantacruz! I just tried appending the '\&tab=text' via my Windows 11 adb terminal but got the same results as before (not searching). Are you saying that this should be fixed in the next upcoming release?

Also, if not specified, shouldn't the default behavior assume the search should do a source search?
Thanks!

**Comment by nsantacruz** [comment]
@Sliicy yes, this will be fixed in the next release (or you can pull master if you're running the app locally). 

I think you're right that the text should be `tab=text` since this is the same default used on web. I'll add that default.
